+ cd ${src}
[ System Version ]
+ python3 ./repro.py
pyassimp: /usr/lib/python3/dist-packages/pyassimp/__init__.py
  dll: <CDLL 'libassimp.so.4', handle 2236ca0 at 0x7f7cafa30e80>

Original: shoulder.dae
[[ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  0.  1.]]
  [[ 0.68592072 -0.3240135   0.65155822  7.48113203]
   [ 0.72767627  0.30542079 -0.61417037 -6.50763988]
   [ 0.          0.89539558  0.4452714   5.34366512]
   [ 0.          0.          0.          1.        ]]
  [[-0.29086459 -0.77110082  0.5663932   4.07624483]
   [ 0.95517123 -0.1998834   0.21839119  1.00545394]
   [-0.05518906  0.60452467  0.79467231  5.903862  ]
   [ 0.          0.          0.          1.        ]]
  [[  6.85920715e-01  -3.24013412e-01   6.51558220e-01   7.48113203e+00]
   [  7.27676272e-01   3.05420786e-01  -6.14170372e-01  -6.50763988e+00]
   [ -4.01132993e-09   8.95395577e-01   4.45271403e-01   5.34366512e+00]
   [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
  [[-0.29086459 -0.77110082  0.56639332  4.07624483]
   [ 0.95517123 -0.1998833   0.21839119  1.00545394]
   [-0.05518906  0.60452467  0.79467231  5.903862  ]
   [ 0.          0.          0.          1.        ]]
  [[ 1.  0.  0.  0.]
   [ 0.  1.  0.  0.]
   [ 0.  0.  1.  0.]
   [ 0.  0.  0.  1.]]
  [[ 1.  0.  0.  0.]
   [ 0.  1.  0.  0.]
   [ 0.  0.  1.  0.]
   [ 0.  0.  0.  1.]]
  [[ 1.  0.  0.  0.]
   [ 0.  1.  0.  0.]
   [ 0.  0.  1.  0.]
   [ 0.  0.  0.  1.]]
Converted: shoulder.obj
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 183, in _init
    init = assimp_struct_inits[type(obj[0])]
KeyError: <class 'pyassimp.structs.LP_Mesh'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./repro.py", line 59, in <module>
    main()
  File "./repro.py", line 54, in main
    convert_mesh("shoulder.dae", "shoulder.obj", "obj")
  File "./repro.py", line 39, in convert_mesh
    scene_new = load_mesh(new_mesh_file)
  File "./repro.py", line 10, in load_mesh
    scene = pyassimp.load(mesh_file)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 319, in load
    scene = _init(model.contents)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 206, in _init
    raise e
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 187, in _init
    call_init(e, target)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 76, in call_init
    _init(obj.contents, obj, caller)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 218, in _init
    _finalize_mesh(self, target)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 410, in _finalize_mesh
    faces = numpy.array([f.indices for f in target.faces], dtype=numpy.int32)
ValueError: setting an array element with a sequence.
